`linera_execution::wasm::wasmer`: don't serialize JS modules (#2758)
We need to do this on native, where we use two different runtimes for
compilation and running, but we don't need to (and indeed can't) do it
on the Web.

Failure to do this causes Wasmer to issue the very surprising error:

    RuntimeError: call stack exhausted during Operation(0)